package dependencies

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// Learner handles learning and remembering successful dependency configurations
type Learner struct {
	memoryDir string
	loader    *Loader
}

// NewLearner creates a new learner instance
func NewLearner(memoryDir string, loader *Loader) *Learner {
	if memoryDir == "" {
		memoryDir = ".installer/memory/dependencies"
	}
	return &Learner{
		memoryDir: memoryDir,
		loader:    loader,
	}
}

// LearnFromSuccess records a successful installation for future reference
func (l *Learner) LearnFromSuccess(node *DependencyNode, installMethod *InstallMethod) error {
	if node == nil || node.ID == "" {
		return fmt.Errorf("invalid dependency node")
	}

	// Create memory entry
	entry := &MemoryEntry{
		ID:        node.ID,
		LearnedAt: time.Now(),
		Source:    "install_success",
		Dependency: DependencyNode{
			ID:              node.ID,
			Name:            node.Name,
			Description:     node.Description,
			Requirements:    node.Requirements,
			Dependencies:    node.Dependencies,
			Platforms:       node.Platforms,
			Provides:        node.Provides,
			InstallMethods:  []InstallMethod{},
			VersionRequirements: node.VersionRequirements,
		},
		SuccessCount: 1,
		LastUsed:     time.Now(),
	}

	// Add the successful install method if provided
	if installMethod != nil {
		entry.Dependency.InstallMethods = []InstallMethod{*installMethod}
	}

	// Check if entry already exists
	existingPath := filepath.Join(l.memoryDir, node.ID+".yaml")
	if data, err := os.ReadFile(existingPath); err == nil {
		var existing MemoryEntry
		if err := yaml.Unmarshal(data, &existing); err == nil {
			// Update existing entry
			entry.SuccessCount = existing.SuccessCount + 1
			entry.Source = existing.Source

			// Merge install methods
			if installMethod != nil {
				methods := existing.Dependency.InstallMethods
				found := false
				for i, m := range methods {
					if m.Type == installMethod.Type {
						// Update existing method with successful one
						methods[i] = *installMethod
						found = true
						break
					}
				}
				if !found {
					methods = append(methods, *installMethod)
				}
				entry.Dependency.InstallMethods = methods
			} else {
				entry.Dependency.InstallMethods = existing.Dependency.InstallMethods
			}

			// Keep other fields from existing if not in new
			if entry.Dependency.Name == "" {
				entry.Dependency.Name = existing.Dependency.Name
			}
			if entry.Dependency.Description == "" {
				entry.Dependency.Description = existing.Dependency.Description
			}
		}
	}

	// Ensure directory exists
	if err := os.MkdirAll(l.memoryDir, 0755); err != nil {
		return fmt.Errorf("failed to create memory directory: %w", err)
	}

	// Write entry
	data, err := yaml.Marshal(entry)
	if err != nil {
		return fmt.Errorf("failed to marshal memory entry: %w", err)
	}

	filename := filepath.Join(l.memoryDir, node.ID+".yaml")
	if err := os.WriteFile(filename, data, 0644); err != nil {
		return fmt.Errorf("failed to write memory file: %w", err)
	}

	return nil
}

// LearnFromAI records a dependency configuration generated by AI
func (l *Learner) LearnFromAI(node *DependencyNode) error {
	if node == nil || node.ID == "" {
		return fmt.Errorf("invalid dependency node")
	}

	entry := &MemoryEntry{
		ID:        node.ID,
		LearnedAt: time.Now(),
		Source:    "ai_generated",
		Dependency: DependencyNode{
			ID:                  node.ID,
			Name:                node.Name,
			Description:         node.Description,
			Requirements:        node.Requirements,
			Dependencies:        node.Dependencies,
			Platforms:           node.Platforms,
			Provides:            node.Provides,
			InstallMethods:      node.InstallMethods,
			VersionRequirements: node.VersionRequirements,
		},
		SuccessCount: 0,
	}

	// Ensure directory exists
	if err := os.MkdirAll(l.memoryDir, 0755); err != nil {
		return fmt.Errorf("failed to create memory directory: %w", err)
	}

	// Write entry
	data, err := yaml.Marshal(entry)
	if err != nil {
		return fmt.Errorf("failed to marshal memory entry: %w", err)
	}

	filename := filepath.Join(l.memoryDir, node.ID+".yaml")
	if err := os.WriteFile(filename, data, 0644); err != nil {
		return fmt.Errorf("failed to write memory file: %w", err)
	}

	return nil
}

// UpdateSuccess increments the success counter for a dependency
func (l *Learner) UpdateSuccess(packageID string) error {
	filename := filepath.Join(l.memoryDir, packageID+".yaml")
	data, err := os.ReadFile(filename)
	if err != nil {
		return fmt.Errorf("dependency %s not found in memory", packageID)
	}

	var entry MemoryEntry
	if err := yaml.Unmarshal(data, &entry); err != nil {
		return fmt.Errorf("failed to parse memory entry: %w", err)
	}

	entry.SuccessCount++
	entry.LastUsed = time.Now()

	updatedData, err := yaml.Marshal(&entry)
	if err != nil {
		return fmt.Errorf("failed to marshal updated entry: %w", err)
	}

	if err := os.WriteFile(filename, updatedData, 0644); err != nil {
		return fmt.Errorf("failed to write updated memory file: %w", err)
	}

	return nil
}

// GetStats returns learning statistics
func (l *Learner) GetStats() (*LearningStats, error) {
	files, err := filepath.Glob(filepath.Join(l.memoryDir, "*.yaml"))
	if err != nil {
		return nil, err
	}

	stats := &LearningStats{
		BySource: make(map[string]int),
	}

	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			continue
		}

		var entry MemoryEntry
		if err := yaml.Unmarshal(data, &entry); err != nil {
			continue
		}

		stats.TotalEntries++
		stats.TotalSuccesses += entry.SuccessCount

		if entry.Source != "" {
			stats.BySource[entry.Source]++
		}

		if !entry.LastUsed.IsZero() {
			if stats.RecentlyUsed == "" || entry.LastUsed.After(stats.LastUsedTime) {
				stats.RecentlyUsed = entry.ID
				stats.LastUsedTime = entry.LastUsed
			}
		}
	}

	return stats, nil
}

// Forget removes a dependency from memory
func (l *Learner) Forget(packageID string) error {
	filenames := []string{
		filepath.Join(l.memoryDir, packageID+".yaml"),
		filepath.Join(l.memoryDir, packageID+".yml"),
	}

	for _, path := range filenames {
		if err := os.Remove(path); err == nil {
			return nil
		}
	}

	return fmt.Errorf("dependency %s not found in memory", packageID)
}

// ForgetAll clears all learned dependencies
func (l *Learner) ForgetAll() error {
	files, err := filepath.Glob(filepath.Join(l.memoryDir, "*.yaml"))
	if err != nil {
		return err
	}

	for _, file := range files {
		os.Remove(file)
	}

	return nil
}

// List returns all learned dependencies
func (l *Learner) List() ([]*MemoryEntry, error) {
	return l.loader.ListMemory()
}

// Get retrieves a specific learned dependency
func (l *Learner) Get(packageID string) (*MemoryEntry, error) {
	filename := filepath.Join(l.memoryDir, packageID+".yaml")
	data, err := os.ReadFile(filename)
	if err != nil {
		return nil, fmt.Errorf("dependency %s not found in memory", packageID)
	}

	var entry MemoryEntry
	if err := yaml.Unmarshal(data, &entry); err != nil {
		return nil, fmt.Errorf("failed to parse memory entry: %w", err)
	}

	return &entry, nil
}

// SetMemoryDir changes the memory directory
func (l *Learner) SetMemoryDir(dir string) {
	l.memoryDir = dir
}

// LearningStats contains statistics about learned dependencies
type LearningStats struct {
	TotalEntries    int            `json:"total_entries"`
	TotalSuccesses  int            `json:"total_successes"`
	BySource        map[string]int `json:"by_source"`
	RecentlyUsed    string         `json:"recently_used,omitempty"`
	LastUsedTime    time.Time      `json:"last_used_time,omitempty"`
}

// UserDefinedConfig represents a user-defined dependency configuration
type UserDefinedConfig struct {
	ID          string           `yaml:"id"`
	Name        string           `yaml:"name"`
	Description string           `yaml:"description,omitempty"`
	Requires    []DependencyRef  `yaml:"requires,omitempty"`
	Platforms   map[string]PlatformConfig `yaml:"platforms,omitempty"`
}

// AddUserDefined adds a user-defined dependency configuration
func (l *Learner) AddUserDefined(config *UserDefinedConfig) error {
	if config.ID == "" {
		return fmt.Errorf("dependency ID is required")
	}

	node := &DependencyNode{
		ID:          config.ID,
		Name:        config.Name,
		Description: config.Description,
		Platforms:   config.Platforms,
	}

	// Convert dependency refs to nodes
	for _, ref := range config.Requires {
		node.Dependencies = append(node.Dependencies, &DependencyNode{
			ID:              ref.ID,
			VersionRequired: ref.Version,
		})
	}

	entry := &MemoryEntry{
		ID:        config.ID,
		LearnedAt: time.Now(),
		Source:    "user_defined",
		Dependency: *node,
	}

	// Ensure directory exists
	if err := os.MkdirAll(l.memoryDir, 0755); err != nil {
		return fmt.Errorf("failed to create memory directory: %w", err)
	}

	data, err := yaml.Marshal(entry)
	if err != nil {
		return fmt.Errorf("failed to marshal entry: %w", err)
	}

	filename := filepath.Join(l.memoryDir, config.ID+".yaml")
	if err := os.WriteFile(filename, data, 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}
